### ISSUE TITLE
Master Branch

### ISSUE THREAD

**Issue by amlwwalker** [openxc/nxpUSBlib#2]
Has everything been merged back into the master branch? Which branch is the latest and most stable? Its just the master branch is behind some other branches on commits?

Thanks

**Comment by peplin** [comment]
The master branch was/is tracking the official release versions from NXP. The default 'next-v0.98' branch is the most up to date that includes my patches still hadn't been merged in yet: https://github.com/openxc/nxpUSBlib#changelog

If you hadn't already seen it, note that NXP deprecate the standalone nxpUSBlib and merged it with their larger LPCOpen package - http://www.lpcware.com/content/project/lpcopen-platform-nxp-lpc-microcontrollers
